apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: todo-app
  namespace: argocd
spec:
  description: Todo App Project
  sourceRepos:
    - https://github.com/Git-Raheman/infra.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: todo-app        # your app namespace
    - server: https://kubernetes.default.svc
      namespace: argocd          # ? ADD THIS
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
spec:
  project: todo-app
  source:
    repoURL: https://github.com/Git-Raheman/infra.git
    targetRevision: main
    path: todo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true