apiVersion: v1
kind: Service
metadata:
  name: todo-app-backend
  namespace: todo-app
spec:
  type: ClusterIP
  selector:
    app: todo-app-backend
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-frontend
  namespace: todo-app
spec:
  type: ClusterIP
  selector:
    app: todo-app-frontend
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-db
  namespace: todo-app
spec:
  type: ClusterIP
  selector:
    app: todo-app-db
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-nginx
  namespace: todo-app
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.50.83
spec:
  type: LoadBalancer
  selector:
    app: todo-app-nginx
  ports:
  - port: 80
    targetPort: 80
