apiVersion: v1
kind: Namespace
metadata:
  name: chat-app
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: chat-app-quota
  namespace: chat-app
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 512Mi
    limits.cpu: "2"
    limits.memory: 512Mi
